using System;
using System.ComponentModel;
using System.ComponentModel.Design;
using System.Collections;
using System.Drawing;
using System.Reflection;
using System.Workflow.ComponentModel.Compiler;
using System.Workflow.ComponentModel.Serialization;
using System.Workflow.ComponentModel;
using System.Workflow.ComponentModel.Design;
using System.Workflow.Runtime;
using System.Workflow.Activities;
using System.Workflow.Activities.Rules;

namespace Chapter06
{
	public sealed partial class Workflow1
	{
		#region Designer generated code
		
		/// <summary> 
		/// Required method for Designer support - do not modify 
		/// the contents of this method with the code editor.
		/// </summary>
		[System.Diagnostics.DebuggerNonUserCode]
		private void InitializeComponent()
		{
            this.CanModifyActivities = true;
            this.faultCode = new System.Workflow.Activities.CodeActivity();
            this.callDisconnectedCode = new System.Workflow.Activities.CodeActivity();
            this.generalFaultHandler = new System.Workflow.ComponentModel.FaultHandlerActivity();
            this.callDisconnectedHandler = new System.Workflow.ComponentModel.FaultHandlerActivity();
            this.faultHandlers = new System.Workflow.ComponentModel.FaultHandlersActivity();
            this.disconnectCallActivity1 = new Microsoft.SpeechServer.Dialog.DisconnectCallActivity();
            this.sayOrder = new Microsoft.SpeechServer.Dialog.StatementActivity();
            this.askSize = new Microsoft.SpeechServer.Dialog.QuestionAnswerActivity();
            this.askColor = new Microsoft.SpeechServer.Dialog.QuestionAnswerActivity();
            this.askProduct = new Microsoft.SpeechServer.Dialog.QuestionAnswerActivity();
            this.sayGreeting = new Microsoft.SpeechServer.Dialog.StatementActivity();
            this.answerCallActivity1 = new Microsoft.SpeechServer.Dialog.AnswerCallActivity();
            // 
            // faultCode
            // 
            this.faultCode.Name = "faultCode";
            this.faultCode.ExecuteCode += new System.EventHandler(this.HandleGeneralFault);
            // 
            // callDisconnectedCode
            // 
            this.callDisconnectedCode.Name = "callDisconnectedCode";
            this.callDisconnectedCode.ExecuteCode += new System.EventHandler(this.HandleCallDisconnected);
            // 
            // generalFaultHandler
            // 
            this.generalFaultHandler.Activities.Add(this.faultCode);
            this.generalFaultHandler.FaultType = typeof(System.Exception);
            this.generalFaultHandler.Name = "generalFaultHandler";
            // 
            // callDisconnectedHandler
            // 
            this.callDisconnectedHandler.Activities.Add(this.callDisconnectedCode);
            this.callDisconnectedHandler.FaultType = typeof(Microsoft.SpeechServer.Dialog.CallDisconnectedException);
            this.callDisconnectedHandler.Name = "callDisconnectedHandler";
            // 
            // faultHandlers
            // 
            this.faultHandlers.Activities.Add(this.callDisconnectedHandler);
            this.faultHandlers.Activities.Add(this.generalFaultHandler);
            this.faultHandlers.Name = "faultHandlers";
            // 
            // disconnectCallActivity1
            // 
            this.disconnectCallActivity1.Name = "disconnectCallActivity1";
            // Generated by GenericSpeechCodeDomSerializer
            // 
            // sayOrder
            // 
            this.sayOrder.Name = "sayOrder";
            this.sayOrder.TurnStarting += new System.EventHandler<Microsoft.SpeechServer.Dialog.TurnStartingEventArgs>(this.sayOrder_TurnStarting);
            // Generated by GenericSpeechCodeDomSerializer
            // 
            // askSize
            // 
            this.askSize.Name = "askSize";
            this.askSize.Prompts.MainPrompt.Id = "Workflow1_askSize_Prompts_Main";
            this.askSize.Prompts.MainPrompt.SetText(this.GetPromptResource(this.askSize.Prompts.MainPrompt.Id));
            this.askSize.Grammars.Add(new Microsoft.SpeechServer.Recognition.Grammar(new System.Uri("Grammars\\Library.grxml", System.UriKind.RelativeOrAbsolute), "Size"));
            // Generated by GenericSpeechCodeDomSerializer
            // 
            // askColor
            // 
            this.askColor.Name = "askColor";
            this.askColor.Prompts.MainPrompt.Id = "Workflow1_askColor_Prompts_Main";
            this.askColor.Prompts.MainPrompt.SetText(this.GetPromptResource(this.askColor.Prompts.MainPrompt.Id));
            this.askColor.Grammars.Add(new Microsoft.SpeechServer.Recognition.Grammar(new System.Uri("Grammars\\Library.grxml", System.UriKind.RelativeOrAbsolute), "Color"));
            // Generated by GenericSpeechCodeDomSerializer
            // 
            // askProduct
            // 
            this.askProduct.Name = "askProduct";
            this.askProduct.Prompts.MainPrompt.Id = "Workflow1_askProduct_Prompts_Main";
            this.askProduct.Prompts.MainPrompt.SetText(this.GetPromptResource(this.askProduct.Prompts.MainPrompt.Id));
            this.askProduct.Grammars.Add(new Microsoft.SpeechServer.Recognition.Grammar(new System.Uri("Grammars\\Library.grxml", System.UriKind.RelativeOrAbsolute), "Product"));
            // Generated by GenericSpeechCodeDomSerializer
            // 
            // sayGreeting
            // 
            this.sayGreeting.Name = "sayGreeting";
            this.sayGreeting.MainPrompt.Id = "Workflow1_sayGreeting_MainPrompt";
            this.sayGreeting.MainPrompt.SetText(this.GetPromptResource(this.sayGreeting.MainPrompt.Id));
            // 
            // answerCallActivity1
            // 
            this.answerCallActivity1.Name = "answerCallActivity1";
            // 
            // Workflow1
            // 
            this.Activities.Add(this.answerCallActivity1);
            this.Activities.Add(this.sayGreeting);
            this.Activities.Add(this.askProduct);
            this.Activities.Add(this.askColor);
            this.Activities.Add(this.askSize);
            this.Activities.Add(this.sayOrder);
            this.Activities.Add(this.disconnectCallActivity1);
            this.Activities.Add(this.faultHandlers);
            this.Name = "Workflow1";
            this.PromptDatabase = new System.Uri("Prompts\\Chapter06Prompts.prompts", System.UriKind.Relative);
            this.CanModifyActivities = false;

        }

		#endregion

        private Microsoft.SpeechServer.Dialog.AnswerCallActivity answerCallActivity1;
        private FaultHandlersActivity faultHandlers;
        private FaultHandlerActivity generalFaultHandler;
        private FaultHandlerActivity callDisconnectedHandler;
        private CodeActivity faultCode;
        private CodeActivity callDisconnectedCode;
        private Microsoft.SpeechServer.Dialog.QuestionAnswerActivity askSize;
        private Microsoft.SpeechServer.Dialog.QuestionAnswerActivity askColor;
        private Microsoft.SpeechServer.Dialog.QuestionAnswerActivity askProduct;
        private Microsoft.SpeechServer.Dialog.StatementActivity sayGreeting;
        private Microsoft.SpeechServer.Dialog.StatementActivity sayOrder;
        private Microsoft.SpeechServer.Dialog.DisconnectCallActivity disconnectCallActivity1;

    }
}
