//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.312
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace NavigableListActivity {
    
    
    public partial class Settings : System.Configuration.ApplicationSettingsBase {
        
        private static Settings s_DefaultInstance;
        
        private static object s_SyncObject = new object();
        
        public static Settings DefaultInstance {
            get {
                if ((Settings.s_DefaultInstance == null)) {
                    System.Threading.Monitor.Enter(Settings.s_SyncObject);
                    if ((Settings.s_DefaultInstance == null)) {
                        try {
                            Settings.s_DefaultInstance = new Settings();
                        }
                        finally {
                            System.Threading.Monitor.Exit(Settings.s_SyncObject);
                        }
                    }
                }
                return Settings.s_DefaultInstance;
            }
        }       
    }
}
