using System;
using System.ComponentModel;
using System.ComponentModel.Design;
using System.Collections;
using System.Drawing;
using System.Reflection;
using System.Workflow.ComponentModel.Compiler;
using System.Workflow.ComponentModel.Serialization;
using System.Workflow.ComponentModel;
using System.Workflow.ComponentModel.Design;
using System.Workflow.Runtime;
using System.Workflow.Activities;
using System.Workflow.Activities.Rules;

namespace Chapter07
{
	public sealed partial class Workflow1
	{
		#region Designer generated code
		
		/// <summary> 
		/// Required method for Designer support - do not modify 
		/// the contents of this method with the code editor.
		/// </summary>
		[System.Diagnostics.DebuggerNonUserCode]
		private void InitializeComponent()
		{
            this.CanModifyActivities = true;
            this.faultCode = new System.Workflow.Activities.CodeActivity();
            this.callDisconnectedCode = new System.Workflow.Activities.CodeActivity();
            this.generalFaultHandler = new System.Workflow.ComponentModel.FaultHandlerActivity();
            this.callDisconnectedHandler = new System.Workflow.ComponentModel.FaultHandlerActivity();
            this.faultHandlers = new System.Workflow.ComponentModel.FaultHandlersActivity();
            this.disconnectCallActivity1 = new Microsoft.SpeechServer.Dialog.DisconnectCallActivity();
            this.sayAppointment = new Microsoft.SpeechServer.Dialog.StatementActivity();
            this.executeWebService = new System.Workflow.Activities.CodeActivity();
            this.askDate = new Microsoft.SpeechServer.Dialog.QuestionAnswerActivity();
            this.answerCallActivity1 = new Microsoft.SpeechServer.Dialog.AnswerCallActivity();
            // 
            // faultCode
            // 
            this.faultCode.Name = "faultCode";
            this.faultCode.ExecuteCode += new System.EventHandler(this.HandleGeneralFault);
            // 
            // callDisconnectedCode
            // 
            this.callDisconnectedCode.Name = "callDisconnectedCode";
            this.callDisconnectedCode.ExecuteCode += new System.EventHandler(this.HandleCallDisconnected);
            // 
            // generalFaultHandler
            // 
            this.generalFaultHandler.Activities.Add(this.faultCode);
            this.generalFaultHandler.FaultType = typeof(System.Exception);
            this.generalFaultHandler.Name = "generalFaultHandler";
            // 
            // callDisconnectedHandler
            // 
            this.callDisconnectedHandler.Activities.Add(this.callDisconnectedCode);
            this.callDisconnectedHandler.FaultType = typeof(Microsoft.SpeechServer.Dialog.CallDisconnectedException);
            this.callDisconnectedHandler.Name = "callDisconnectedHandler";
            // 
            // faultHandlers
            // 
            this.faultHandlers.Activities.Add(this.callDisconnectedHandler);
            this.faultHandlers.Activities.Add(this.generalFaultHandler);
            this.faultHandlers.Name = "faultHandlers";
            // 
            // disconnectCallActivity1
            // 
            this.disconnectCallActivity1.Name = "disconnectCallActivity1";
            // Generated by GenericSpeechCodeDomSerializer
            // 
            // sayAppointment
            // 
            this.sayAppointment.Name = "sayAppointment";
            this.sayAppointment.TurnStarting += new System.EventHandler<Microsoft.SpeechServer.Dialog.TurnStartingEventArgs>(this.sayAppointment_TurnStarting);
            // 
            // executeWebService
            // 
            this.executeWebService.Name = "executeWebService";
            this.executeWebService.ExecuteCode += new System.EventHandler(this.executeWebService_ExecuteCode);
            // Generated by GenericSpeechCodeDomSerializer
            // 
            // askDate
            // 
            this.askDate.Name = "askDate";
            this.askDate.Prompts.MainPrompt.Id = "Workflow1_askDate_Prompts_Main";
            this.askDate.Prompts.MainPrompt.SetText(this.GetPromptResource(this.askDate.Prompts.MainPrompt.Id));
            this.askDate.Grammars.Add(new Microsoft.SpeechServer.Recognition.Grammar(new System.Uri("Grammars\\Library.grxml", System.UriKind.RelativeOrAbsolute), "Date"));
            // 
            // answerCallActivity1
            // 
            this.answerCallActivity1.Name = "answerCallActivity1";
            // 
            // Workflow1
            // 
            this.Activities.Add(this.answerCallActivity1);
            this.Activities.Add(this.askDate);
            this.Activities.Add(this.executeWebService);
            this.Activities.Add(this.sayAppointment);
            this.Activities.Add(this.disconnectCallActivity1);
            this.Activities.Add(this.faultHandlers);
            this.Name = "Workflow1";
            this.CanModifyActivities = false;

        }

		#endregion

        private Microsoft.SpeechServer.Dialog.AnswerCallActivity answerCallActivity1;
        private FaultHandlersActivity faultHandlers;
        private FaultHandlerActivity generalFaultHandler;
        private FaultHandlerActivity callDisconnectedHandler;
        private CodeActivity faultCode;
        private CodeActivity callDisconnectedCode;
        private CodeActivity executeWebService;
        private Microsoft.SpeechServer.Dialog.QuestionAnswerActivity askDate;
        private Microsoft.SpeechServer.Dialog.StatementActivity sayAppointment;
        private Microsoft.SpeechServer.Dialog.DisconnectCallActivity disconnectCallActivity1;


    }
}
